# Generated by Django 3.1 on 2021-05-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='biography',
            field=models.TextField(blank=True, null=True),
        ),
    ]
