# Generated by Django 3.1 on 2021-05-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_patientprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=150),
        ),
    ]
