# Generated by Django 3.1 on 2021-05-15 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctorprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Clinic_name', models.CharField(blank=True, max_length=150, null=True)),
                ('Clinic_Address', models.CharField(blank=True, max_length=150, null=True)),
                ('Degree', models.CharField(blank=True, max_length=450, null=True)),
                ('college', models.CharField(blank=True, max_length=350, null=True)),
                ('yearDonne', models.DateField(blank=True, null=True)),
                ('Hospital_name', models.CharField(blank=True, max_length=450, null=True)),
                ('from_year', models.DateField(blank=True, null=True)),
                ('to_year', models.DateField(blank=True, null=True)),
                ('Designation', models.CharField(blank=True, max_length=450, null=True)),
                ('Award_got', models.CharField(blank=True, max_length=450, null=True)),
                ('year', models.DateField(blank=True, null=True)),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic', to=settings.AUTH_USER_MODEL)),
                ('Services', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='Doctor',
        ),
        migrations.RemoveField(
            model_name='education',
            name='Doctor',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='Doctor',
        ),
        migrations.RemoveField(
            model_name='works',
            name='Doctor',
        ),
        migrations.RemoveField(
            model_name='works',
            name='Services',
        ),
        migrations.DeleteModel(
            name='Awards',
        ),
        migrations.DeleteModel(
            name='Clinic',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.DeleteModel(
            name='Works',
        ),
    ]
